Phx 1671 instansiate in unittest
iVantage/ivantagemail pull request #1
Opened 2020-05-11 20:45 UTC by Jdstuart13

2020-05-14 22:03 UTC, evsheffield requested changes
Thanks for all of your work on this, James! I've left some comments but the main things I think we should look at are:

- Let's remove the `npm-debug.log` file. This can probably be added to our `.gitignore` as well.
- I'd like to make sure that we are still compatible with PHP 5.6 based on how our dependencies are set. Can we look into the `doctrine-orm-module` versions to make sure we are using a version that says it supports PHP 5.6?

2020-05-14 22:03 UTC, evsheffield commented on composer.json
> -    "php": ">=5.3.3",
The PHP dependency is probably safe to leave in for now, right? And once all is said and done we'll be able to bump it up to PHP 7.x too!

2020-05-14 22:03 UTC, evsheffield commented on composer.json
> +    "doctrine/doctrine-orm-module": "^1.1",
I think specified as is we might end up pulling a version that requires a newer version of PHP. e.g. https://github.com/doctrine/DoctrineORMModule/blob/1.1.8/composer.json only works with PHP 7. If we can keep things compatible with PHP 5.6 for now that will help our transition plan. Looks like perhaps 1.1.5 is the last version that supports PHP 5.6.

2020-05-14 22:03 UTC, evsheffield commented on phpunit.xml
> +         convertWarningsToExceptions="false"
Just curious, what sorts of warnings were we getting that were causing problems?

2020-05-14 22:03 UTC, evsheffield commented on tests/IvantageMailTest/Service/PostOfficeTest.php
> +                return new \IvantageMail\Tasks\EmailTask($email, $mailman, $headers);
Small style point but it looks like the indentation is a bit too deep here.

2020-05-14 22:03 UTC, evsheffield commented on tests/bootstrap.php
> +        $_emptyConfig = new ServiceManagerConfig();
Another small style point but we generally don't prefix any of our PHP variable names with underscores.

2020-05-14 22:03 UTC, evsheffield commented on tests/IvantageMailTest/Service/PostOfficeTest.php
> +        Bootstrap::getServiceManager();
Since we're not using the service manager in this test we probably don't need to call this any more.

2020-05-14 22:03 UTC, evsheffield commented on tests/bootstrap.php
> +        $emptyConfig = $_emptyConfig->ToArray();
The capitalization of `ToArray` looks a little off to me just going by how they usually name their functions using camelCase. Should it be `toArray()`?

2020-05-15 14:04 UTC, Jdstuart13 commented on phpunit.xml
> +         convertWarningsToExceptions="false"
I think this is no longer relevant

2020-05-18 15:19 UTC, evsheffield commented
Thanks for the updates, James! I ran the unit tests locally and it worked like a charm! Before final approval and merge there's a few clean-up items I'd love for us to include.

- Remove the `npm-debug.log` file and add to `.gitignore`
- Update the README to say ZF3 instead of ZF2.
- Add the `composer.lock` file to version control and remove from `.gitignore`. This is now recommended by composer and will help make sure that our dependencies stay locked into the set you were using that are functioning correctly.

2020-05-18 18:49 UTC, Jdstuart13 commented
Good call evan, sorry I lost those earlier 😅

2020-05-18 19:19 UTC, evsheffield approved these changes
Looks good! When you're ready you can merge these changes and tag v3.0.0 (looks like we already had a 2.0 🤷; 1.0 was probably lost in the SVN transition). And remember to follow our freshly updated commit message guidelines 🙏

2020-05-18 19:37 UTC, merged